name: Generate Directory Markdown

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Run Directory Tree Generator
        uses: MaximilianRau/directory-tree-generator@v2
        with:
          path: "Angular,Bash,C#,C++.C,Java,Js,Python,Rust"
          extensions: ".html,.ts,.scss,.sh,.cs,.cpp,.c,.java,.js,.py,.rs"
          show-extensions: true
          output: "DIRECTORY.md

      - name: Commit and push changes
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add DIRECTORY.md
          git diff --cached --quiet || git commit -m "Update DIRECTORY.md"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
